baseURL = "https://system2.io/"
languageCode = "en-us"
title = "System2"
theme = "hugo-theme-air"

[author]
  name = "eastwood"

[params]
  description = "The brain dump of a lazy developer"
  author = "eastwd"
  logo = ""
  hideHUGOSupport = true